### ISSUE TITLE
Tweaks required to build pico-dualsense on my system.

### ISSUE THREAD

**Issue by ideacrystals** [cadouthat/pico-dualsense#1]
Thank you for a very useful library! I now have the provided example working perfectly with my Sony Dualsense controller model CFI-ZCT1W. 
Being new to Pico development, I solved build issues on my M1 Mac with some trial-and-error...

dual sense_I2cap.h:
```
#include "btstack.h".
// Produced a compilation error when trying to find the file btstack.h.
// So I dirty-fixed it by including a full path instead, i.e.
#include "~/pico/pico-sdk/lib/btstack/src/btstack.h"
```
CMakeLists.txt:
```
// During compilation, the file btstack_config.h could not be found, so I added the line,
target_include_directories(pico_dualsense PRIVATE ${CMAKE_CURRENT_LIST_DIR} ) # For btstack config.
```
With those two changes made, the library built error-free for me.

**Comment by cadouthat** [comment]
This seems like a CMake issue and I don't know of any fix on this end - maybe someone in the Pico SDK forum would have ideas.

Good to hear you found a work-around, I'll close this for now but others can chime in if they experience the same problem.
